#!/usr/bin/env python3
"""
Complete Pokémon Database (286 Pokémon)
Contains types, evolution stages, and special characteristics
"""

# Complete Pokémon database with all 286 Pokémon
POKEMON_DB = {
    # Generation 1 (001-151)
    'Bulbasaur': {'types': ['GRASS', 'POISON'], 'stage': 1, 'evo_stage': 3, 'category': 'starter'},
    'Ivysaur': {'types': ['GRASS', 'POISON'], 'stage': 2, 'evo_stage': 3, 'category': 'starter'},
    'Venusaur': {'types': ['GRASS', 'POISON'], 'stage': 3, 'evo_stage': 3, 'category': 'starter'},
    'Charmander': {'types': ['FIRE'], 'stage': 1, 'evo_stage': 3, 'category': 'starter'},
    'Charmeleon': {'types': ['FIRE'], 'stage': 2, 'evo_stage': 3, 'category': 'starter'},
    'Charizard': {'types': ['FIRE', 'FLYING'], 'stage': 3, 'evo_stage': 3, 'category': 'starter'},
    'Squirtle': {'types': ['WATER'], 'stage': 1, 'evo_stage': 3, 'category': 'starter'},
    'Wartortle': {'types': ['WATER'], 'stage': 2, 'evo_stage': 3, 'category': 'starter'},
    'Blastoise': {'types': ['WATER'], 'stage': 3, 'evo_stage': 3, 'category': 'starter'},
    'CATERPIE': {'types': ['BUG'], 'stage': 1, 'evo_stage': 3, 'category': 'early_bug'},
    'METAPOD': {'types': ['BUG'], 'stage': 2, 'evo_stage': 3, 'category': 'early_bug'},
    'BUTTERFREE': {'types': ['BUG', 'FLYING'], 'stage': 3, 'evo_stage': 3, 'category': 'early_bug'},
    'WEEDLE': {'types': ['BUG', 'POISON'], 'stage': 1, 'evo_stage': 3, 'category': 'early_bug'},
    'KAKUNA': {'types': ['BUG', 'POISON'], 'stage': 2, 'evo_stage': 3, 'category': 'early_bug'},
    'BEEDRILL': {'types': ['BUG', 'POISON'], 'stage': 3, 'evo_stage': 3, 'category': 'early_bug'},
    'PIDGEY': {'types': ['NORMAL', 'FLYING'], 'stage': 1, 'evo_stage': 3, 'category': 'early_bird'},
    'PIDGEOTTO': {'types': ['NORMAL', 'FLYING'], 'stage': 2, 'evo_stage': 3, 'category': 'early_bird'},
    'PIDGEOT': {'types': ['NORMAL', 'FLYING'], 'stage': 3, 'evo_stage': 3, 'category': 'early_bird'},
    'RATTATA': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 2, 'category': 'early_normal'},
    'RATICATE': {'types': ['NORMAL'], 'stage': 2, 'evo_stage': 2, 'category': 'early_normal'},
    'SPEAROW': {'types': ['NORMAL', 'FLYING'], 'stage': 1, 'evo_stage': 2, 'category': 'early_bird'},
    'FEAROW': {'types': ['NORMAL', 'FLYING'], 'stage': 2, 'evo_stage': 2, 'category': 'early_bird'},
    'EKANS': {'types': ['POISON'], 'stage': 1, 'evo_stage': 2, 'category': 'early_poison'},
    'ARBOK': {'types': ['POISON'], 'stage': 2, 'evo_stage': 2, 'category': 'early_poison'},
    'PIKACHU': {'types': ['ELECTRIC'], 'stage': 1, 'evo_stage': 2, 'category': 'iconic'},
    'RAICHU': {'types': ['ELECTRIC'], 'stage': 2, 'evo_stage': 2, 'category': 'iconic'},
    'SANDSHREW': {'types': ['GROUND'], 'stage': 1, 'evo_stage': 2, 'category': 'early_ground'},
    'SANDSLASH': {'types': ['GROUND'], 'stage': 2, 'evo_stage': 2, 'category': 'early_ground'},
    'NIDORAN_F': {'types': ['POISON'], 'stage': 1, 'evo_stage': 3, 'category': 'early_poison'},
    'NIDORINA': {'types': ['POISON'], 'stage': 2, 'evo_stage': 3, 'category': 'early_poison'},
    'NIDOQUEEN': {'types': ['POISON', 'GROUND'], 'stage': 3, 'evo_stage': 3, 'category': 'early_poison'},
    'NIDORAN_M': {'types': ['POISON'], 'stage': 1, 'evo_stage': 3, 'category': 'early_poison'},
    'NIDORINO': {'types': ['POISON'], 'stage': 2, 'evo_stage': 3, 'category': 'early_poison'},
    'NIDOKING': {'types': ['POISON', 'GROUND'], 'stage': 3, 'evo_stage': 3, 'category': 'early_poison'},
    'CLEFAIRY': {'types': ['FAIRY'], 'stage': 1, 'evo_stage': 2, 'category': 'fairy'},
    'CLEFABLE': {'types': ['FAIRY'], 'stage': 2, 'evo_stage': 2, 'category': 'fairy'},
    'VULPIX': {'types': ['FIRE'], 'stage': 1, 'evo_stage': 2, 'category': 'early_fire'},
    'NINETALES': {'types': ['FIRE'], 'stage': 2, 'evo_stage': 2, 'category': 'early_fire'},
    'JIGGLYPUFF': {'types': ['NORMAL', 'FAIRY'], 'stage': 1, 'evo_stage': 2, 'category': 'fairy'},
    'WIGGLYTUFF': {'types': ['NORMAL', 'FAIRY'], 'stage': 2, 'evo_stage': 2, 'category': 'fairy'},
    'ZUBAT': {'types': ['POISON', 'FLYING'], 'stage': 1, 'evo_stage': 3, 'category': 'cave'},
    'GOLBAT': {'types': ['POISON', 'FLYING'], 'stage': 2, 'evo_stage': 3, 'category': 'cave'},
    'ODDISH': {'types': ['GRASS', 'POISON'], 'stage': 1, 'evo_stage': 3, 'category': 'early_grass'},
    'GLOOM': {'types': ['GRASS', 'POISON'], 'stage': 2, 'evo_stage': 3, 'category': 'early_grass'},
    'VILEPLUME': {'types': ['GRASS', 'POISON'], 'stage': 3, 'evo_stage': 3, 'category': 'early_grass'},
    'PARAS': {'types': ['BUG', 'GRASS'], 'stage': 1, 'evo_stage': 2, 'category': 'early_bug'},
    'PARASECT': {'types': ['BUG', 'GRASS'], 'stage': 2, 'evo_stage': 2, 'category': 'early_bug'},
    'VENONAT': {'types': ['BUG', 'POISON'], 'stage': 1, 'evo_stage': 2, 'category': 'early_bug'},
    'VENOMOTH': {'types': ['BUG', 'POISON'], 'stage': 2, 'evo_stage': 2, 'category': 'early_bug'},
    'DIGLETT': {'types': ['GROUND'], 'stage': 1, 'evo_stage': 2, 'category': 'early_ground'},
    'DUGTRIO': {'types': ['GROUND'], 'stage': 2, 'evo_stage': 2, 'category': 'early_ground'},
    'MEOWTH': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 2, 'category': 'early_normal'},
    'PERSIAN': {'types': ['NORMAL'], 'stage': 2, 'evo_stage': 2, 'category': 'early_normal'},
    'PSYDUCK': {'types': ['WATER'], 'stage': 1, 'evo_stage': 2, 'category': 'early_water'},
    'GOLDUCK': {'types': ['WATER'], 'stage': 2, 'evo_stage': 2, 'category': 'early_water'},
    'MANKEY': {'types': ['FIGHTING'], 'stage': 1, 'evo_stage': 2, 'category': 'early_fighting'},
    'PRIMEAPE': {'types': ['FIGHTING'], 'stage': 2, 'evo_stage': 2, 'category': 'early_fighting'},
    'GROWLITHE': {'types': ['FIRE'], 'stage': 1, 'evo_stage': 2, 'category': 'early_fire'},
    'ARCANINE': {'types': ['FIRE'], 'stage': 2, 'evo_stage': 2, 'category': 'early_fire'},
    'POLIWAG': {'types': ['WATER'], 'stage': 1, 'evo_stage': 3, 'category': 'early_water'},
    'POLIWHIRL': {'types': ['WATER'], 'stage': 2, 'evo_stage': 3, 'category': 'early_water'},
    'POLIWRATH': {'types': ['WATER', 'FIGHTING'], 'stage': 3, 'evo_stage': 3, 'category': 'early_water'},
    'ABRA': {'types': ['PSYCHIC'], 'stage': 1, 'evo_stage': 3, 'category': 'psychic'},
    'KADABRA': {'types': ['PSYCHIC'], 'stage': 2, 'evo_stage': 3, 'category': 'psychic'},
    'ALAKAZAM': {'types': ['PSYCHIC'], 'stage': 3, 'evo_stage': 3, 'category': 'psychic'},
    'MACHOP': {'types': ['FIGHTING'], 'stage': 1, 'evo_stage': 3, 'category': 'early_fighting'},
    'MACHOKE': {'types': ['FIGHTING'], 'stage': 2, 'evo_stage': 3, 'category': 'early_fighting'},
    'MACHAMP': {'types': ['FIGHTING'], 'stage': 3, 'evo_stage': 3, 'category': 'early_fighting'},
    'BELLSPROUT': {'types': ['GRASS', 'POISON'], 'stage': 1, 'evo_stage': 3, 'category': 'early_grass'},
    'WEEPINBELL': {'types': ['GRASS', 'POISON'], 'stage': 2, 'evo_stage': 3, 'category': 'early_grass'},
    'VICTREEBEL': {'types': ['GRASS', 'POISON'], 'stage': 3, 'evo_stage': 3, 'category': 'early_grass'},
    'TENTACOOL': {'types': ['WATER', 'POISON'], 'stage': 1, 'evo_stage': 2, 'category': 'water'},
    'TENTACRUEL': {'types': ['WATER', 'POISON'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'GEODUDE': {'types': ['ROCK', 'GROUND'], 'stage': 1, 'evo_stage': 3, 'category': 'early_rock'},
    'GRAVELER': {'types': ['ROCK', 'GROUND'], 'stage': 2, 'evo_stage': 3, 'category': 'early_rock'},
    'GOLEM': {'types': ['ROCK', 'GROUND'], 'stage': 3, 'evo_stage': 3, 'category': 'early_rock'},
    'PONYTA': {'types': ['FIRE'], 'stage': 1, 'evo_stage': 2, 'category': 'early_fire'},
    'RAPIDASH': {'types': ['FIRE'], 'stage': 2, 'evo_stage': 2, 'category': 'early_fire'},
    'SLOWPOKE': {'types': ['WATER', 'PSYCHIC'], 'stage': 1, 'evo_stage': 2, 'category': 'water'},
    'SLOWBRO': {'types': ['WATER', 'PSYCHIC'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'MAGNEMITE': {'types': ['ELECTRIC', 'STEEL'], 'stage': 1, 'evo_stage': 2, 'category': 'electric'},
    'MAGNETON': {'types': ['ELECTRIC', 'STEEL'], 'stage': 2, 'evo_stage': 2, 'category': 'electric'},
    'FARFETCHD': {'types': ['NORMAL', 'FLYING'], 'stage': 1, 'evo_stage': 1, 'category': 'unique'},
    'DODUO': {'types': ['NORMAL', 'FLYING'], 'stage': 1, 'evo_stage': 2, 'category': 'early_bird'},
    'DODRIO': {'types': ['NORMAL', 'FLYING'], 'stage': 2, 'evo_stage': 2, 'category': 'early_bird'},
    'SEEL': {'types': ['WATER'], 'stage': 1, 'evo_stage': 2, 'category': 'water'},
    'DEWGONG': {'types': ['WATER', 'ICE'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'GRIMER': {'types': ['POISON'], 'stage': 1, 'evo_stage': 2, 'category': 'poison'},
    'MUK': {'types': ['POISON'], 'stage': 2, 'evo_stage': 2, 'category': 'poison'},
    'SHELLDER': {'types': ['WATER'], 'stage': 1, 'evo_stage': 2, 'category': 'water'},
    'CLOYSTER': {'types': ['WATER', 'ICE'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'GASTLY': {'types': ['GHOST', 'POISON'], 'stage': 1, 'evo_stage': 3, 'category': 'ghost'},
    'HAUNTER': {'types': ['GHOST', 'POISON'], 'stage': 2, 'evo_stage': 3, 'category': 'ghost'},
    'GENGAR': {'types': ['GHOST', 'POISON'], 'stage': 3, 'evo_stage': 3, 'category': 'ghost'},
    'ONIX': {'types': ['ROCK', 'GROUND'], 'stage': 1, 'evo_stage': 2, 'category': 'early_rock'},
    'DROWZEE': {'types': ['PSYCHIC'], 'stage': 1, 'evo_stage': 2, 'category': 'psychic'},
    'HYPNO': {'types': ['PSYCHIC'], 'stage': 2, 'evo_stage': 2, 'category': 'psychic'},
    'KRABBY': {'types': ['WATER'], 'stage': 1, 'evo_stage': 2, 'category': 'water'},
    'KINGLER': {'types': ['WATER'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'VOLTORB': {'types': ['ELECTRIC'], 'stage': 1, 'evo_stage': 2, 'category': 'electric'},
    'ELECTRODE': {'types': ['ELECTRIC'], 'stage': 2, 'evo_stage': 2, 'category': 'electric'},
    'EXEGGCUTE': {'types': ['GRASS', 'PSYCHIC'], 'stage': 1, 'evo_stage': 2, 'category': 'grass'},
    'EXEGGUTOR': {'types': ['GRASS', 'PSYCHIC'], 'stage': 2, 'evo_stage': 2, 'category': 'grass'},
    'CUBONE': {'types': ['GROUND'], 'stage': 1, 'evo_stage': 2, 'category': 'ground'},
    'MAROWAK': {'types': ['GROUND'], 'stage': 2, 'evo_stage': 2, 'category': 'ground'},
    'HITMONLEE': {'types': ['FIGHTING'], 'stage': 1, 'evo_stage': 1, 'category': 'fighting'},
    'HITMONCHAN': {'types': ['FIGHTING'], 'stage': 1, 'evo_stage': 1, 'category': 'fighting'},
    'LICKITUNG': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 2, 'category': 'normal'},
    'KOFFING': {'types': ['POISON'], 'stage': 1, 'evo_stage': 2, 'category': 'poison'},
    'WEEZING': {'types': ['POISON'], 'stage': 2, 'evo_stage': 2, 'category': 'poison'},
    'RHYHORN': {'types': ['GROUND', 'ROCK'], 'stage': 1, 'evo_stage': 2, 'category': 'ground'},
    'RHYDON': {'types': ['GROUND', 'ROCK'], 'stage': 2, 'evo_stage': 2, 'category': 'ground'},
    'CHANSEY': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 2, 'category': 'normal'},
    'TANGELA': {'types': ['GRASS'], 'stage': 1, 'evo_stage': 2, 'category': 'grass'},
    'KANGASKHAN': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 1, 'category': 'normal'},
    'HORSEA': {'types': ['WATER'], 'stage': 1, 'evo_stage': 2, 'category': 'water'},
    'SEADRA': {'types': ['WATER'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'GOLDEEN': {'types': ['WATER'], 'stage': 1, 'evo_stage': 2, 'category': 'water'},
    'SEAKING': {'types': ['WATER'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'STARYU': {'types': ['WATER'], 'stage': 1, 'evo_stage': 2, 'category': 'water'},
    'STARMIE': {'types': ['WATER', 'PSYCHIC'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'MR_MIME': {'types': ['PSYCHIC', 'FAIRY'], 'stage': 1, 'evo_stage': 2, 'category': 'psychic'},
    'SCYTHER': {'types': ['BUG', 'FLYING'], 'stage': 1, 'evo_stage': 2, 'category': 'bug'},
    'JYNX': {'types': ['ICE', 'PSYCHIC'], 'stage': 1, 'evo_stage': 1, 'category': 'ice'},
    'ELECTABUZZ': {'types': ['ELECTRIC'], 'stage': 1, 'evo_stage': 2, 'category': 'electric'},
    'MAGMAR': {'types': ['FIRE'], 'stage': 1, 'evo_stage': 2, 'category': 'fire'},
    'PINSIR': {'types': ['BUG'], 'stage': 1, 'evo_stage': 2, 'category': 'bug'},
    'TAUROS': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 1, 'category': 'normal'},
    'MAGIKARP': {'types': ['WATER'], 'stage': 1, 'evo_stage': 2, 'category': 'magikarp'},
    'GYARADOS': {'types': ['WATER', 'FLYING'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'LAPRAS': {'types': ['WATER', 'ICE'], 'stage': 1, 'evo_stage': 1, 'category': 'water'},
    'DITTO': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 1, 'category': 'unique'},
    'EEVEE': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 1, 'category': 'eevee'},
    'VAPOREON': {'types': ['WATER'], 'stage': 2, 'evo_stage': 1, 'category': 'eeveelution'},
    'JOLTEON': {'types': ['ELECTRIC'], 'stage': 2, 'evo_stage': 1, 'category': 'eeveelution'},
    'FLAREON': {'types': ['FIRE'], 'stage': 2, 'evo_stage': 1, 'category': 'eeveelution'},
    'PORYGON': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 2, 'category': 'normal'},
    'OMANYTE': {'types': ['ROCK', 'WATER'], 'stage': 1, 'evo_stage': 2, 'category': 'fossil'},
    'OMASTAR': {'types': ['ROCK', 'WATER'], 'stage': 2, 'evo_stage': 2, 'category': 'fossil'},
    'KABUTO': {'types': ['ROCK', 'WATER'], 'stage': 1, 'evo_stage': 2, 'category': 'fossil'},
    'KABUTOPS': {'types': ['ROCK', 'WATER'], 'stage': 2, 'evo_stage': 2, 'category': 'fossil'},
    'AERODACTYL': {'types': ['ROCK', 'FLYING'], 'stage': 1, 'evo_stage': 1, 'category': 'fossil'},
    'SNORLAX': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 1, 'category': 'normal'},
    'ARTICUNO': {'types': ['ICE', 'FLYING'], 'stage': 1, 'evo_stage': 1, 'category': 'legendary'},
    'ZAPDOS': {'types': ['ELECTRIC', 'FLYING'], 'stage': 1, 'evo_stage': 1, 'category': 'legendary'},
    'MOLTRES': {'types': ['FIRE', 'FLYING'], 'stage': 1, 'evo_stage': 1, 'category': 'legendary'},
    'DRATINI': {'types': ['DRAGON'], 'stage': 1, 'evo_stage': 3, 'category': 'dragon'},
    'DRAGONAIR': {'types': ['DRAGON'], 'stage': 2, 'evo_stage': 3, 'category': 'dragon'},
    'DRAGONITE': {'types': ['DRAGON', 'FLYING'], 'stage': 3, 'evo_stage': 3, 'category': 'pseudo_legendary'},
    'MEWTWO': {'types': ['PSYCHIC'], 'stage': 1, 'evo_stage': 1, 'category': 'legendary'},
    'MEW': {'types': ['PSYCHIC'], 'stage': 1, 'evo_stage': 1, 'category': 'mythic'},
    
    # Generation 2 (152-251)
    'CHIKORITA': {'types': ['GRASS'], 'stage': 1, 'evo_stage': 3, 'category': 'starter'},
    'BAYLEEF': {'types': ['GRASS'], 'stage': 2, 'evo_stage': 3, 'category': 'starter'},
    'MEGANIUM': {'types': ['GRASS'], 'stage': 3, 'evo_stage': 3, 'category': 'starter'},
    'CYNDAQUIL': {'types': ['FIRE'], 'stage': 1, 'evo_stage': 3, 'category': 'starter'},
    'QUILAVA': {'types': ['FIRE'], 'stage': 2, 'evo_stage': 3, 'category': 'starter'},
    'TYPHLOSION': {'types': ['FIRE'], 'stage': 3, 'evo_stage': 3, 'category': 'starter'},
    'TOTODILE': {'types': ['WATER'], 'stage': 1, 'evo_stage': 3, 'category': 'starter'},
    'CROCONAW': {'types': ['WATER'], 'stage': 2, 'evo_stage': 3, 'category': 'starter'},
    'FERALIGATR': {'types': ['WATER'], 'stage': 3, 'evo_stage': 3, 'category': 'starter'},
    'SENTRET': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 2, 'category': 'early_normal'},
    'FURRET': {'types': ['NORMAL'], 'stage': 2, 'evo_stage': 2, 'category': 'early_normal'},
    'HOOTHOOT': {'types': ['NORMAL', 'FLYING'], 'stage': 1, 'evo_stage': 2, 'category': 'early_bird'},
    'NOCTOWL': {'types': ['NORMAL', 'FLYING'], 'stage': 2, 'evo_stage': 2, 'category': 'early_bird'},
    'LEDYBA': {'types': ['BUG', 'FLYING'], 'stage': 1, 'evo_stage': 2, 'category': 'early_bug'},
    'LEDIAN': {'types': ['BUG', 'FLYING'], 'stage': 2, 'evo_stage': 2, 'category': 'early_bug'},
    'SPINARAK': {'types': ['BUG', 'POISON'], 'stage': 1, 'evo_stage': 2, 'category': 'early_bug'},
    'ARIADOS': {'types': ['BUG', 'POISON'], 'stage': 2, 'evo_stage': 2, 'category': 'early_bug'},
    'CROBAT': {'types': ['POISON', 'FLYING'], 'stage': 3, 'evo_stage': 3, 'category': 'cave'},
    'CHINCHOU': {'types': ['WATER', 'ELECTRIC'], 'stage': 1, 'evo_stage': 2, 'category': 'water'},
    'LANTURN': {'types': ['WATER', 'ELECTRIC'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'PICHU': {'types': ['ELECTRIC'], 'stage': 1, 'evo_stage': 2, 'category': 'baby'},
    'CLEFFA': {'types': ['FAIRY'], 'stage': 1, 'evo_stage': 2, 'category': 'baby'},
    'IGGLYBUFF': {'types': ['NORMAL', 'FAIRY'], 'stage': 1, 'evo_stage': 2, 'category': 'baby'},
    'TOGEPI': {'types': ['FAIRY'], 'stage': 1, 'evo_stage': 2, 'category': 'baby'},
    'TOGETIC': {'types': ['FAIRY', 'FLYING'], 'stage': 2, 'evo_stage': 2, 'category': 'fairy'},
    'NATU': {'types': ['PSYCHIC', 'FLYING'], 'stage': 1, 'evo_stage': 2, 'category': 'psychic'},
    'XATU': {'types': ['PSYCHIC', 'FLYING'], 'stage': 2, 'evo_stage': 2, 'category': 'psychic'},
    'MAREEP': {'types': ['ELECTRIC'], 'stage': 1, 'evo_stage': 3, 'category': 'electric'},
    'FLAAFFY': {'types': ['ELECTRIC'], 'stage': 2, 'evo_stage': 3, 'category': 'electric'},
    'AMPHAROS': {'types': ['ELECTRIC'], 'stage': 3, 'evo_stage': 3, 'category': 'electric'},
    'BELLOSSOM': {'types': ['GRASS'], 'stage': 3, 'evo_stage': 3, 'category': 'grass'},
    'MARILL': {'types': ['WATER', 'FAIRY'], 'stage': 1, 'evo_stage': 2, 'category': 'water'},
    'AZUMARILL': {'types': ['WATER', 'FAIRY'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'SUDOWOODO': {'types': ['ROCK'], 'stage': 1, 'evo_stage': 1, 'category': 'rock'},
    'POLITOED': {'types': ['WATER'], 'stage': 3, 'evo_stage': 3, 'category': 'water'},
    'HOPPIP': {'types': ['GRASS', 'FLYING'], 'stage': 1, 'evo_stage': 3, 'category': 'grass'},
    'SKIPLOOM': {'types': ['GRASS', 'FLYING'], 'stage': 2, 'evo_stage': 3, 'category': 'grass'},
    'JUMPLUFF': {'types': ['GRASS', 'FLYING'], 'stage': 3, 'evo_stage': 3, 'category': 'grass'},
    'AIPOM': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 2, 'category': 'normal'},
    'SUNKERN': {'types': ['GRASS'], 'stage': 1, 'evo_stage': 2, 'category': 'grass'},
    'SUNFLORA': {'types': ['GRASS'], 'stage': 2, 'evo_stage': 2, 'category': 'grass'},
    'YANMA': {'types': ['BUG', 'FLYING'], 'stage': 1, 'evo_stage': 2, 'category': 'bug'},
    'WOOPER': {'types': ['WATER', 'GROUND'], 'stage': 1, 'evo_stage': 2, 'category': 'water'},
    'QUAGSIRE': {'types': ['WATER', 'GROUND'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'ESPEON': {'types': ['PSYCHIC'], 'stage': 2, 'evo_stage': 1, 'category': 'eeveelution'},
    'UMBREON': {'types': ['DARK'], 'stage': 2, 'evo_stage': 1, 'category': 'eeveelution'},
    'MURKROW': {'types': ['DARK', 'FLYING'], 'stage': 1, 'evo_stage': 2, 'category': 'dark'},
    'SLOWKING': {'types': ['WATER', 'PSYCHIC'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'MISDREAVUS': {'types': ['GHOST'], 'stage': 1, 'evo_stage': 2, 'category': 'ghost'},
    'UNOWN': {'types': ['PSYCHIC'], 'stage': 1, 'evo_stage': 1, 'category': 'unique'},
    'WOBBUFFET': {'types': ['PSYCHIC'], 'stage': 1, 'evo_stage': 1, 'category': 'psychic'},
    'GIRAFARIG': {'types': ['NORMAL', 'PSYCHIC'], 'stage': 1, 'evo_stage': 2, 'category': 'normal'},
    'PINECO': {'types': ['BUG'], 'stage': 1, 'evo_stage': 2, 'category': 'bug'},
    'FORRETRESS': {'types': ['BUG', 'STEEL'], 'stage': 2, 'evo_stage': 2, 'category': 'bug'},
    'DUNSPARCE': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 2, 'category': 'normal'},
    'GLIGAR': {'types': ['GROUND', 'FLYING'], 'stage': 1, 'evo_stage': 2, 'category': 'ground'},
    'STEELIX': {'types': ['STEEL', 'GROUND'], 'stage': 2, 'evo_stage': 2, 'category': 'steel'},
    'SNUBBULL': {'types': ['FAIRY'], 'stage': 1, 'evo_stage': 2, 'category': 'fairy'},
    'GRANBULL': {'types': ['FAIRY'], 'stage': 2, 'evo_stage': 2, 'category': 'fairy'},
    'QWILFISH': {'types': ['WATER', 'POISON'], 'stage': 1, 'evo_stage': 2, 'category': 'water'},
    'SCIZOR': {'types': ['BUG', 'STEEL'], 'stage': 2, 'evo_stage': 2, 'category': 'bug'},
    'SHUCKLE': {'types': ['BUG', 'ROCK'], 'stage': 1, 'evo_stage': 1, 'category': 'bug'},
    'HERACROSS': {'types': ['BUG', 'FIGHTING'], 'stage': 1, 'evo_stage': 1, 'category': 'bug'},
    'SNEASEL': {'types': ['DARK', 'ICE'], 'stage': 1, 'evo_stage': 2, 'category': 'dark'},
    'TEDDIURSA': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 2, 'category': 'normal'},
    'URSARING': {'types': ['NORMAL'], 'stage': 2, 'evo_stage': 2, 'category': 'normal'},
    'SLUGMA': {'types': ['FIRE', 'ROCK'], 'stage': 1, 'evo_stage': 2, 'category': 'fire'},
    'MAGCARGO': {'types': ['FIRE', 'ROCK'], 'stage': 2, 'evo_stage': 2, 'category': 'fire'},
    'SWINUB': {'types': ['ICE', 'GROUND'], 'stage': 1, 'evo_stage': 2, 'category': 'ice'},
    'PILOSWINE': {'types': ['ICE', 'GROUND'], 'stage': 2, 'evo_stage': 2, 'category': 'ice'},
    'CORSOLA': {'types': ['WATER', 'ROCK'], 'stage': 1, 'evo_stage': 1, 'category': 'water'},
    'REMORAID': {'types': ['WATER'], 'stage': 1, 'evo_stage': 2, 'category': 'water'},
    'OCTILLERY': {'types': ['WATER'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'DELIBIRD': {'types': ['ICE', 'FLYING'], 'stage': 1, 'evo_stage': 1, 'category': 'ice'},
    'MANTINE': {'types': ['WATER', 'FLYING'], 'stage': 1, 'evo_stage': 1, 'category': 'water'},
    'SKARMORY': {'types': ['STEEL', 'FLYING'], 'stage': 1, 'evo_stage': 1, 'category': 'steel'},
    'HOUNDOUR': {'types': ['DARK', 'FIRE'], 'stage': 1, 'evo_stage': 2, 'category': 'dark'},
    'HOUNDOOM': {'types': ['DARK', 'FIRE'], 'stage': 2, 'evo_stage': 2, 'category': 'dark'},
    'KINGDRA': {'types': ['WATER', 'DRAGON'], 'stage': 2, 'evo_stage': 2, 'category': 'dragon'},
    'PHANPY': {'types': ['GROUND'], 'stage': 1, 'evo_stage': 2, 'category': 'ground'},
    'DONPHAN': {'types': ['GROUND'], 'stage': 2, 'evo_stage': 2, 'category': 'ground'},
    'PORYGON2': {'types': ['NORMAL'], 'stage': 2, 'evo_stage': 2, 'category': 'normal'},
    'STANTLER': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 1, 'category': 'normal'},
    'TYROGUE': {'types': ['FIGHTING'], 'stage': 1, 'evo_stage': 2, 'category': 'baby'},
    'HITMONTOP': {'types': ['FIGHTING'], 'stage': 2, 'evo_stage': 1, 'category': 'fighting'},
    'SMOOCHUM': {'types': ['ICE', 'PSYCHIC'], 'stage': 1, 'evo_stage': 2, 'category': 'baby'},
    'ELEKID': {'types': ['ELECTRIC'], 'stage': 1, 'evo_stage': 2, 'category': 'baby'},
    'MAGBY': {'types': ['FIRE'], 'stage': 1, 'evo_stage': 2, 'category': 'baby'},
    'MILTANK': {'types': ['NORMAL'], 'stage': 1, 'evo_stage': 1, 'category': 'normal'},
    'BLISSEY': {'types': ['NORMAL'], 'stage': 2, 'evo_stage': 2, 'category': 'normal'},
    'RAIKOU': {'types': ['ELECTRIC'], 'stage': 1, 'evo_stage': 1, 'category': 'legendary'},
    'ENTEI': {'types': ['FIRE'], 'stage': 1, 'evo_stage': 1, 'category': 'legendary'},
    'SUICUNE': {'types': ['WATER'], 'stage': 1, 'evo_stage': 1, 'category': 'legendary'},
    'LARVITAR': {'types': ['ROCK', 'GROUND'], 'stage': 1, 'evo_stage': 3, 'category': 'pseudo_legendary'},
    'PUPITAR': {'types': ['ROCK', 'GROUND'], 'stage': 2, 'evo_stage': 3, 'category': 'pseudo_legendary'},
    'TYRANITAR': {'types': ['ROCK', 'DARK'], 'stage': 3, 'evo_stage': 3, 'category': 'pseudo_legendary'},
    'LUGIA': {'types': ['PSYCHIC', 'FLYING'], 'stage': 1, 'evo_stage': 1, 'category': 'legendary'},
    'HO_OH': {'types': ['FIRE', 'FLYING'], 'stage': 1, 'evo_stage': 1, 'category': 'legendary'},
    'CELEBI': {'types': ['PSYCHIC', 'GRASS'], 'stage': 1, 'evo_stage': 1, 'category': 'mythic'},
    
    # Cross-generational evolutions (252-286)
    'CROBAT': {'types': ['POISON', 'FLYING'], 'stage': 3, 'evo_stage': 3, 'category': 'cave'},
    'BELLOSSOM': {'types': ['GRASS'], 'stage': 3, 'evo_stage': 3, 'category': 'grass'},
    'POLITOED': {'types': ['WATER'], 'stage': 3, 'evo_stage': 3, 'category': 'water'},
    'ESPEON': {'types': ['PSYCHIC'], 'stage': 2, 'evo_stage': 1, 'category': 'eeveelution'},
    'UMBREON': {'types': ['DARK'], 'stage': 2, 'evo_stage': 1, 'category': 'eeveelution'},
    'SLOWKING': {'types': ['WATER', 'PSYCHIC'], 'stage': 2, 'evo_stage': 2, 'category': 'water'},
    'SCIZOR': {'types': ['BUG', 'STEEL'], 'stage': 2, 'evo_stage': 2, 'category': 'bug'},
    'STEELIX': {'types': ['STEEL', 'GROUND'], 'stage': 2, 'evo_stage': 2, 'category': 'steel'},
    'KINGDRA': {'types': ['WATER', 'DRAGON'], 'stage': 2, 'evo_stage': 2, 'category': 'dragon'},
    'PORYGON2': {'types': ['NORMAL'], 'stage': 2, 'evo_stage': 2, 'category': 'normal'},
    'BLISSEY': {'types': ['NORMAL'], 'stage': 2, 'evo_stage': 2, 'category': 'normal'},
    
    # New Pokémon (287-286 in this hack)
    'ANNIHILAPE': {'types': ['FIGHTING', 'GHOST'], 'stage': 3, 'evo_stage': 3, 'category': 'new'},
    'AZURILL': {'types': ['NORMAL', 'FAIRY'], 'stage': 1, 'evo_stage': 2, 'category': 'new'},
    'CLODSIRE': {'types': ['GROUND', 'POISON'], 'stage': 2, 'evo_stage': 2, 'category': 'new'},
    'CORSOLA_G': {'types': ['GHOST'], 'stage': 1, 'evo_stage': 2, 'category': 'new'},
    'CURSOLA': {'types': ['GHOST'], 'stage': 2, 'evo_stage': 2, 'category': 'new'},
    'DUDUNSPARCE': {'types': ['NORMAL'], 'stage': 2, 'evo_stage': 2, 'category': 'new'},
    'FARIGIRAF': {'types': ['NORMAL', 'PSYCHIC'], 'stage': 2, 'evo_stage': 2, 'category': 'new'},
    'GLISCOR': {'types': ['GROUND', 'FLYING'], 'stage': 2, 'evo_stage': 2, 'category': 'new'},
    'KLEAVOR': {'types': ['BUG', 'ROCK'], 'stage': 2, 'evo_stage': 2, 'category': 'new'},
    'LICKILICKY': {'types': ['NORMAL'], 'stage': 2, 'evo_stage': 2, 'category': 'new'},
    'MANTYKE': {'types': ['WATER', 'FLYING'], 'stage': 1, 'evo_stage': 2, 'category': 'new'},
    'MIME_JR': {'types': ['PSYCHIC', 'FAIRY'], 'stage': 1, 'evo_stage': 2, 'category': 'new'},
    'NINETALES_A': {'types': ['ICE', 'FAIRY'], 'stage': 2, 'evo_stage': 2, 'category': 'new'},
    'OVERQWIL': {'types': ['DARK', 'POISON'], 'stage': 2, 'evo_stage': 2, 'category': 'new'},
    'VULPIX_A': {'types': ['ICE'], 'stage': 1, 'evo_stage': 2, 'category': 'new'},
    'WOOPER_P': {'types': ['POISON', 'GROUND'], 'stage': 1, 'evo_stage': 2, 'category': 'new'},
    'WYRDEER': {'types': ['NORMAL', 'PSYCHIC'], 'stage': 2, 'evo_stage': 2, 'category': 'new'},
    'YANMEGA': {'types': ['BUG', 'FLYING'], 'stage': 2, 'evo_stage': 2, 'category': 'new'},
}

# Special move assignments for specific Pokémon
SPECIAL_MOVES = {
    # Starter ultimate moves
    'VENUSAUR': ['FRENZY_PLANT'],
    'CHARIZARD': ['BLAST_BURN'],
    'BLASTOISE': ['HYDRO_CANNON'],
    'MEGANIUM': ['FRENZY_PLANT'],
    'TYPHLOSION': ['BLAST_BURN'],
    'FERALIGATR': ['HYDRO_CANNON'],
    
    # Legendary signature moves
    'MEWTWO': ['PSYSTRIKE'],
    'MEW': ['ANCIENT_POWER'],
    'LUGIA': ['AEROBLAST'],
    'HO_OH': ['SACRED_FIRE'],
    'CELEBI': ['HEALING_WISH'],
    
    # Pseudo-legendary signature moves
    'DRAGONITE': ['DRAGON_ASCENT'],
    'TYRANITAR': ['SAND_STORM'],
    
    # Eeveelution signature moves
    'VAPOREON': ['HYDRO_PUMP'],
    'JOLTEON': ['THUNDER'],
    'FLAREON': ['FIRE_BLAST'],
    'ESPEON': ['PSYCHIC_M'],
    'UMBREON': ['DARK_PULSE'],
    
    # New Pokémon signature moves
    'ANNIHILAPE': ['RAGE_FIST', 'FINAL_CHANCE'],
    'GLISCOR': ['ACROBATICS'],
    'YANMEGA': ['BUG_BUZZ'],
    'KLEAVOR': ['STONE_AXE'],
    'NINETALES_A': ['AURORA_VEIL'],
    'OVERQWIL': ['DARK_PULSE'],
}

# Category-based move priorities
CATEGORY_PRIORITIES = {
    'starter': {
        'early': ['basic', 'status'],
        'mid': ['intermediate', 'coverage'],
        'late': ['advanced', 'signature'],
        'final': ['ultimate', 'signature']
    },
    'legendary': {
        'early': ['intermediate'],
        'mid': ['advanced', 'coverage'],
        'late': ['ultimate', 'signature'],
        'final': ['ultimate', 'signature']
    },
    'pseudo_legendary': {
        'early': ['basic', 'intermediate'],
        'mid': ['advanced', 'coverage'],
        'late': ['ultimate', 'signature'],
        'final': ['ultimate', 'signature']
    },
    'eeveelution': {
        'early': ['basic', 'status'],
        'mid': ['intermediate', 'type_specific'],
        'late': ['advanced', 'signature'],
        'final': ['ultimate', 'signature']
    },
    'baby': {
        'early': ['basic', 'status'],
        'mid': ['basic', 'intermediate'],
        'late': ['intermediate'],
        'final': ['advanced']
    },
    'early_normal': {
        'early': ['basic', 'status'],
        'mid': ['intermediate'],
        'late': ['advanced'],
        'final': ['advanced']
    },
    'early_bird': {
        'early': ['basic', 'flying'],
        'mid': ['intermediate', 'flying'],
        'late': ['advanced', 'flying'],
        'final': ['ultimate', 'flying']
    },
    'early_bug': {
        'early': ['basic', 'bug'],
        'mid': ['intermediate', 'bug'],
        'late': ['advanced', 'bug'],
        'final': ['ultimate', 'bug']
    },
    'water': {
        'early': ['basic', 'water'],
        'mid': ['intermediate', 'water'],
        'late': ['advanced', 'water'],
        'final': ['ultimate', 'water']
    },
    'fire': {
        'early': ['basic', 'fire'],
        'mid': ['intermediate', 'fire'],
        'late': ['advanced', 'fire'],
        'final': ['ultimate', 'fire']
    },
    'grass': {
        'early': ['basic', 'grass'],
        'mid': ['intermediate', 'grass'],
        'late': ['advanced', 'grass'],
        'final': ['ultimate', 'grass']
    },
    'electric': {
        'early': ['basic', 'electric'],
        'mid': ['intermediate', 'electric'],
        'late': ['advanced', 'electric'],
        'final': ['ultimate', 'electric']
    },
    'psychic': {
        'early': ['basic', 'psychic'],
        'mid': ['intermediate', 'psychic'],
        'late': ['advanced', 'psychic'],
        'final': ['ultimate', 'psychic']
    },
    'fighting': {
        'early': ['basic', 'fighting'],
        'mid': ['intermediate', 'fighting'],
        'late': ['advanced', 'fighting'],
        'final': ['ultimate', 'fighting']
    },
    'dragon': {
        'early': ['basic', 'dragon'],
        'mid': ['intermediate', 'dragon'],
        'late': ['advanced', 'dragon'],
        'final': ['ultimate', 'dragon']
    },
    'dark': {
        'early': ['basic', 'dark'],
        'mid': ['intermediate', 'dark'],
        'late': ['advanced', 'dark'],
        'final': ['ultimate', 'dark']
    },
    'steel': {
        'early': ['basic', 'steel'],
        'mid': ['intermediate', 'steel'],
        'late': ['advanced', 'steel'],
        'final': ['ultimate', 'steel']
    },
    'fairy': {
        'early': ['basic', 'fairy'],
        'mid': ['intermediate', 'fairy'],
        'late': ['advanced', 'fairy'],
        'final': ['ultimate', 'fairy']
    },
    'ghost': {
        'early': ['basic', 'ghost'],
        'mid': ['intermediate', 'ghost'],
        'late': ['advanced', 'ghost'],
        'final': ['ultimate', 'ghost']
    },
    'ice': {
        'early': ['basic', 'ice'],
        'mid': ['intermediate', 'ice'],
        'late': ['advanced', 'ice'],
        'final': ['ultimate', 'ice']
    },
    'poison': {
        'early': ['basic', 'poison'],
        'mid': ['intermediate', 'poison'],
        'late': ['advanced', 'poison'],
        'final': ['ultimate', 'poison']
    },
    'ground': {
        'early': ['basic', 'ground'],
        'mid': ['intermediate', 'ground'],
        'late': ['advanced', 'ground'],
        'final': ['ultimate', 'ground']
    },
    'rock': {
        'early': ['basic', 'rock'],
        'mid': ['intermediate', 'rock'],
        'late': ['advanced', 'rock'],
        'final': ['ultimate', 'rock']
    },
    'flying': {
        'early': ['basic', 'flying'],
        'mid': ['intermediate', 'flying'],
        'late': ['advanced', 'flying'],
        'final': ['ultimate', 'flying']
    },
    'bug': {
        'early': ['basic', 'bug'],
        'mid': ['intermediate', 'bug'],
        'late': ['advanced', 'bug'],
        'final': ['ultimate', 'bug']
    },
    'normal': {
        'early': ['basic', 'normal'],
        'mid': ['intermediate', 'normal'],
        'late': ['advanced', 'normal'],
        'final': ['ultimate', 'normal']
    },
    'cave': {
        'early': ['basic', 'poison'],
        'mid': ['intermediate', 'poison'],
        'late': ['advanced', 'poison'],
        'final': ['ultimate', 'poison']
    },
    'fossil': {
        'early': ['basic', 'rock'],
        'mid': ['intermediate', 'rock'],
        'late': ['advanced', 'rock'],
        'final': ['ultimate', 'rock']
    },
    'magikarp': {
        'early': ['basic'],
        'mid': ['basic'],
        'late': ['intermediate'],
        'final': ['ultimate']
    },
    'unique': {
        'early': ['basic', 'unique'],
        'mid': ['intermediate', 'unique'],
        'late': ['advanced', 'unique'],
        'final': ['ultimate', 'unique']
    },
    'iconic': {
        'early': ['basic', 'iconic'],
        'mid': ['intermediate', 'iconic'],
        'late': ['advanced', 'iconic'],
        'final': ['ultimate', 'iconic']
    },
    'mythic': {
        'early': ['intermediate'],
        'mid': ['advanced', 'coverage'],
        'late': ['ultimate', 'signature'],
        'final': ['ultimate', 'signature']
    },
    'new': {
        'early': ['basic', 'type_specific'],
        'mid': ['intermediate', 'type_specific'],
        'late': ['advanced', 'signature'],
        'final': ['ultimate', 'signature']
    }
}

print(f"Loaded {len(POKEMON_DB)} Pokémon")
print(f"Categories: {len(set(p['category'] for p in POKEMON_DB.values()))}")
print("Database loaded successfully!")
